# Generated by Django 4.2.4 on 2023-08-03 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_users_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='passwd',
            field=models.CharField(max_length=256),
        ),
    ]
