# Generated by Django 4.2.4 on 2023-08-03 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_users_passwd'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=60)),
                ('data', models.CharField(max_length=60)),
                ('time', models.CharField(max_length=60)),
                ('location', models.CharField(max_length=60)),
                ('image', models.CharField(max_length=60)),
                ('is_liked', models.CharField(max_length=60)),
                ('user_id', models.CharField(max_length=60)),
            ],
        ),
    ]
