# Generated by Django 4.2.4 on 2023-08-04 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_data_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='is_liked',
            field=models.BooleanField(default=False),
        ),
    ]
