# Generated by Django 4.2.4 on 2023-08-04 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_data_is_liked'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='liked',
            field=models.CharField(default='[]', max_length=256),
        ),
    ]
