# Generated by Django 4.2.4 on 2023-08-04 07:18

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_users_liked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='liked',
            field=django_mysql.models.ListCharField(models.CharField(max_length=10), max_length=66, size=6),
        ),
    ]
